filebeat.inputs:
  - type: filestream
    id: docker-logs
    paths:
      - /var/lib/docker/containers/*/*-json.log
    parsers:
      - container:
          stream: all
    processors:
      - add_docker_metadata: ~
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "medassist-logs-%{+yyyy.MM.dd}"

setup.template.enabled: false
setup.ilm.enabled: false
